apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ if .Values.TEST }}gol-tracker-test{{ else }}gol-tracker{{ end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gol-tracker
  template:
    metadata:
      labels:
        app: gol-tracker
    spec:
      imagePullSecrets:
        - name: github-registry
        - namespace: argocd
      containers:
      - name: gol-tracker
        image: {{ if .Values.TEST }}ghcr.io/zetericks/go-league:test{{ else }}ghcr.io/zetericks/go-league:main{{ end }}
        env:
        - name: DISCORD_BOT_TOKEN
          value: "${DISCORD_BOT_TOKEN}"
        - name: RIOT_API_TOKEN
          value: "${RIOT_API_TOKEN}"
        - name: API_RATE_LIMIT_2_MINUTE
          value: "${API_RATE_LIMIT_2_MINUTE}"
        - name: API_RATE_LIMIT_SECOND
          value: "${API_RATE_LIMIT_SECOND}"
        - name: POSTGRES_USER
          value: "${POSTGRES_USER}"
        - name: POSTGRES_PASSWORD
          value: "${POSTGRES_PASSWORD}"
        - name: POSTGRES_DB
          value: "${POSTGRES_DB}"
        - name: POSTGRES_HOST
          value: "${POSTGRES_HOST}"
        - name: LOG_LEVEL
          value: "${LOG_LEVEL}"
        - name: DEBUG
          value: "${DEBUG}"
---
{{- if .Values.DEBUG }}
apiVersion: v1
kind: Service
metadata:
  name: gol-tracker
spec:
  selector:
    app: gol-tracker
  ports:
    - protocol: TCP
      port: 6060
      targetPort: 6060
{{- end }}