apiVersion: apps/v1
kind: Deployment
metadata:
  name: gol-tracker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gol-tracker
  template:
    metadata:
      labels:
        app: gol-tracker
    spec:
      containers:
      - name: gol-tracker
        image: ghcr.io/zetericks/go-league:${IMAGE_TAG}
        env:
        - name: DISCORD_BOT_TOKEN
          valueFrom:
            secretKeyRef:
              name: discord-bot-secrets
              key: DISCORD_BOT_TOKEN
        - name: RIOT_API_TOKEN
          valueFrom:
            secretKeyRef:
              name: discord-bot-secrets
              key: RIOT_API_TOKEN
        - name: API_RATE_LIMIT_2_MINUTE
          value: "${API_RATE_LIMIT_2_MINUTE}"
        - name: API_RATE_LIMIT_SECOND
          value: "${API_RATE_LIMIT_SECOND}"
        - name: GITHUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: discord-bot-secrets
              key: GITHUB_TOKEN
        - name: GITHUB_USERNAME
          value: "${GITHUB_USERNAME}"
        - name: DEVELOPMENT
          value: "${DEVELOPMENT}"
        - name: POSTGRES_USER
          value: "${POSTGRES_USER}"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: discord-bot-secrets
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          value: "${POSTGRES_DB}"
        - name: POSTGRES_HOST
          value: "${POSTGRES_HOST}"
        - name: LOG_LEVEL
          value: "${LOG_LEVEL}"
---
apiVersion: v1
kind: Service
metadata:
  name: gol-tracker
spec:
  selector:
    app: gol-tracker
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080